### ISSUE TITLE
NoMethodError - undefined method `html_safe' for String

### ISSUE THREAD

**Issue by kokizzu** [awesome-print/awesome_print#137]
The error message:

```
== Sinatra/1.4.3 has taken the stage on 65002 for production with backup from Thin
NoMethodError - undefined method `html_safe' for "<pre><kbd style=\"color:blue\">0</kbd></pre>":String:
        /usr/lib/ruby/gems/2.0.0/gems/awesome_print-1.2.0/lib/awesome_print/core_ext/kernel.rb:13:in `ai'
        /home/asd/Dropbox/testproject/test1.rb:109:in `output='
        ./appserver.rb:81:in `block in <main>'
```

the source code `testproject/test1.rb` line 108-110

```
  def output= val
    @json[:output] = val.awesome_inspect(html:true) unless val.nil?
  end
```

**Comment by D-side** [comment]
Yeah, the "we're gonna use it with Rails only anyway" disease :D

A workaround is to pull in `gem 'activesupport'` and selectively require that functionality like so:

    require 'active_support/core_ext/string/output_safety'

But hey, it's an implicit dependency.
