### ISSUE TITLE
1.6.0 breaks compatibility with Sequel

### ISSUE THREAD

**Issue by trevor** [awesome-print/awesome_print#202]
* Gemfile
```ruby
source 'http://rubygems.org'
gem 'sequel'
gem 'sqlite3'
#gem 'awesome_print', "1.2.0"
gem 'awesome_print', "1.6.0"
```

* Example
```ruby
require "sequel"
require "awesome_print"
DB = Sequel.sqlite
DB.create_table :items do
  primary_key :id
end
items = DB[:items]
ap items
```

Works with 1.2.0, but 1.6.0 and 1.6.1 throw:

```
ArgumentError: wrong number of arguments (0 for 1..2)
  from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.25.0/lib/sequel/dataset/actions.rb:687:in `to_hash'
  from /usr/local/lib/ruby/gems/2.2.0/gems/awesome_print-1.6.0/lib/awesome_print/formatter.rb:67:in `awesome_self'
  from /usr/local/lib/ruby/gems/2.2.0/gems/awesome_print-1.6.0/lib/awesome_print/formatter.rb:28:in `format'
  from /usr/local/lib/ruby/gems/2.2.0/gems/awesome_print-1.6.0/lib/awesome_print/inspector.rb:137:in `unnested'
  from /usr/local/lib/ruby/gems/2.2.0/gems/awesome_print-1.6.0/lib/awesome_print/inspector.rb:104:in `awesome'
  from /usr/local/lib/ruby/gems/2.2.0/gems/awesome_print-1.6.0/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
  from /usr/local/lib/ruby/gems/2.2.0/gems/awesome_print-1.6.0/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
```

**Comment by solyaris** [comment]
+1

**Comment by waldyr** [comment]
I'm marking this and #204 as resolved. Tested with 1.7.0 and it now works properly.

![screen shot 2016-06-19 at 1 15 11 pm](https://cloud.githubusercontent.com/assets/1893997/16178493/f1c06e42-361f-11e6-93b4-bca2fa6d93a9.png)

**Comment by gerrywastaken** [comment]
@waldyr good work closing fixed tickets!

As always, if anybody is still running into this issue on the latest build, then please let us know by tagging us in a comment.
