### ISSUE TITLE
connection.execute error

### ISSUE THREAD

**Issue by Friend-LGA** [awesome-print/awesome_print#223]
```ruby
2.2.2 :002 > ActiveRecord::Base.connection.select_all("SELECT * FROM users")
   (0.4ms)  SELECT * FROM users
NoMethodError: undefined method `keys' for #<Array:0x0000000777ca98>
	from /home/user/.rvm/gems/ruby-2.2.2/gems/awesome_print-1.6.1/lib/awesome_print/formatter.rb:103:in `awesome_hash'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/awesome_print-1.6.1/lib/awesome_print/formatter.rb:67:in `awesome_self'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/awesome_print-1.6.1/lib/awesome_print/formatter.rb:28:in `format'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/awesome_print-1.6.1/lib/awesome_print/inspector.rb:137:in `unnested'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/awesome_print-1.6.1/lib/awesome_print/inspector.rb:104:in `awesome'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/awesome_print-1.6.1/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/awesome_print-1.6.1/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
	from /home/user/.rvm/gems/ruby-2.2.2/gems/awesome_print-1.6.1/lib/awesome_print/inspector.rb:31:in `output_value'
```

**Comment by waldyr** [comment]
Same error of #215 you can either use master or add option `raw: true`
