### ISSUE TITLE
Investigate merge fatal error

### ISSUE THREAD

**Issue by gerrywastaken** [awesome-print/awesome_print#268]
I ran into this issue yesterday. I'm recording it here until I have time to look into it.

```
/Users/gerry/.gem/ruby/2.2.3/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:169:in `merge!': no implicit conversion of Array into Hash (TypeError)
	from /Users/gerry/.gem/ruby/2.2.3/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:169:in `merge_options!'
	from /Users/gerry/.gem/ruby/2.2.3/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:92:in `initialize'
	from /Users/gerry/.gem/ruby/2.2.3/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:9:in `new'
	from /Users/gerry/.gem/ruby/2.2.3/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:9:in `ai'
	from /Users/gerry/.gem/ruby/2.2.3/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
	from foo.sh:152:in `<main>'
```

**Comment by Numbluk** [comment]
As far as I can tell, this has to do with the options hash that was passed in here:  `ap object, options = { } ` which is then sent here:

```ruby
# inspector.rb
def merge_options!(options = {})
    @options[:color].merge!(options.delete(:color) || {})
    @options.merge!(options)
end
```

`options.delete(:color)` returned an array or `options` itself was an array. If you think this case is exceptional enough, it could be rescued with an appropriate error message if you think it'd be more informative to tell the user they aren't passing in the correct type of options.

Otherwise, this issue can probably be closed.
