### ISSUE TITLE
aws-sdk incompatible with awesome_print

### ISSUE THREAD

**Issue by iainelder** [awesome-print/awesome_print#275]
I installed [awesome_print](https://github.com/awesome-print/awesome_print) as the default formatter in irb, and now I can't view responses from the AWS API. Formatting the response fails with an error like this:

```
NameError: undefined method `to_hash' for class `Seahorse::Client::Response'
```

My .irbrc file looks like this:

```
require 'awesome_print'
AwesomePrint.irb!
```

To reproduce the issue and see the expected behavior:
- start irb requiring the aws-sdk module
- try to print any API response (fails with the NameError)
- try to print the `to_hash` output of the same response (shows the expected behavior)

```
$ irb -r aws-sdk
irb(main):001:0> iam = Aws::IAM::Client.new
#<Aws::IAM::Client>
irb(main):002:0> iam.list_users
NameError: undefined method `to_hash' for class `Seahorse::Client::Response'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/formatter.rb:122:in `method'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/formatter.rb:122:in `convert_to_hash'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/formatter.rb:55:in `awesome_self'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/formatter.rb:36:in `format'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:148:in `unnested'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:115:in `awesome'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
    from /Users/iainelder/.gem/ruby/2.0.0/gems/awesome_print-1.7.0/lib/awesome_print/inspector.rb:33:in `output_value'
    from /usr/bin/irb:12:in `<main>'
irb(main):003:0> iam.list_users.to_hash
{
           :users => [
        [ 0] {
                   :path => "/",
              :user_name => ...,
                :user_id => ...,
                    :arn => ...,
            :create_date => ...
        },
        ...
}
```

So the `to_hash` method does exist, and I can call it explicitly as a workaround. But it seems like awesome_print isn't calling it correctly.

I already raised the problem as [issue 1316](https://github.com/aws/aws-sdk-ruby/issues/1316) with the aws-sdk maintainers if you need more info from them.

**Comment by gerrywastaken** [comment]
@iainelder According to https://github.com/aws/aws-sdk-ruby/issues/1316#issuecomment-259015306 the object in the AWS sdk tells us they respond_to to_hash, but then throw an error when we attempt to do so.

**Comment by gerrywastaken** [comment]
@iainelder It appears this was fixed in the aws sdk (see the ticket you mentioned). I'm closing this for now, but if the issue is still occurring for you on the latest version of the SDK, please alert me and I'll reopen this.

**Comment by trevorrowe** [comment]
I did some digging into this. I found the root cause of why the error was being raised in the SDK when awesome_print attempted to format a `Seahorse::Client::Response` object. The client response acts as a delegator for response data. There are a small number of methods available on response. It uses `#method_missing` to delegate methods to its `@data` object which is normally a struct.  Because it uses method missing it also defines `#respond_to?`. 

The response object definitely responds to `#to_hash`.

```ruby
resp.respond_to?(:to_hash) #=> true
resp.to_hash #=> {...}
```

The problem is that it does not actually define a `#to_hash` method.

```ruby
resp.method(:to_hash) #=> raises a NameError as there is no :to_hash method on the response
```

I believe that awesome_print's assumption that if an object responds to a method that it must define it is causing the issue. The purpose of method missing is to handle messages dispatched to an object for which there is no method defined. The purpose of respond to is to indicate what messages the object will answer, not what methods it defines.

awesome_print calls `#respond_to?` to see if an object is hash-like:
https://github.com/awesome-print/awesome_print/issues/275

It then calls `#method(:to_hash)` so that it can check the arity of the method. Presumably this is to avoid calling `#to_hash` with the wrong number of arguments:
https://github.com/awesome-print/awesome_print/blob/master/lib/awesome_print/formatter.rb#L114

Lastly it calls `#to_hash` and then inspects the returned object to see if it responds to certain hash methods (check to see if it quacks like a hash):
https://github.com/awesome-print/awesome_print/blob/master/lib/awesome_print/formatter.rb#L119

All along this code path, it bails out by returning a `nil` value in the case of failure so that it call fall back on `#inspect`. It seems like a reasonable fix would be to replace the call to `#respond_to?` with a check against the object's public methods:

```
diff --git a/lib/awesome_print/formatter.rb b/lib/awesome_print/formatter.rb
index 0d59304..6b610bd 100644
--- a/lib/awesome_print/formatter.rb
+++ b/lib/awesome_print/formatter.rb
@@ -107,7 +107,7 @@ module AwesomePrint
     # Utility methods.
     #------------------------------------------------------------------------------
     def convert_to_hash(object)
-      if !object.respond_to?(:to_hash)
+      if !object.public_methods.include?(:to_hash)
         return nil
       end
```

This minor change resolves the issue with awesome printing an AWS SDK for Ruby response object. If the public methods list constains `:to_hash`, then you should be able to get the method to check its arity.

On an semi-related  note, I also changed the SDK's implementation to not use #method_missing, and to instead to use Ruby's stdlib `Delegator`. This also works around the issue. Regardless, I believe the change above is still semantically correct. I'll go ahead and submit a pull-request with the change so it can be discussed.

**Comment by gerrywastaken** [comment]
My response is here: https://github.com/awesome-print/awesome_print/pull/285#issuecomment-263048237
