### ISSUE TITLE
ArgumentError: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by Irostovsky** [awesome-print/awesome_print#330]
```
[1] pry(main)> uri = URI('http://www.example.com/todo.cgi')
#<URI::HTTP http://www.example.com/todo.cgi>
[2] pry(main)> req = Net::HTTP::Post.new(uri, {q: 'asd'})
(pry) output error: #<ArgumentError: wrong number of arguments (given 1, expected 0)>
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:114:in `convert_to_hash'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:47:in `awesome_self'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:28:in `format'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:115:in `unnested'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:74:in `awesome'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/awesome_print-1.8.0/lib/awesome_print/custom_defaults.rb:45:in `block in pry!'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/pry-0.11.3/lib/pry/pry_instance.rb:367:in `show_result'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/pry-0.11.3/lib/pry/pry_instance.rb:336:in `block in handle_line'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/pry-0.11.3/lib/pry/pry_class.rb:395:in `critical_section'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/pry-0.11.3/lib/pry/pry_instance.rb:335:in `handle_line'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/pry-0.11.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `catch'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `block in eval'
/Users/ir/.rvm/gems/ruby-2.3.1@guestready/gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `catch'
```

The reason that instance of the `Net::HTTP::Post POST` has the method `method`.  And into https://github.com/awesome-print/awesome_print/blob/master/lib/awesome_print/formatter.rb#L114 tries to call `method` with param.

```
[1] pry(main)> uri = URI('http://www.example.com/todo.cgi')
=> #<URI::HTTP http://www.example.com/todo.cgi>
[2] pry(main)> req = Net::HTTP::Post.new(uri, {q: 'asd'})
=> #<Net::HTTP::Post POST>
[3] pry(main)> req.method
=> "POST"
```

**Comment by sunsations** [comment]
+1

**Comment by sunsations** [comment]
Works for me, if I disable the IRB Integration (https://github.com/awesome-print/awesome_print#irb-integration)

**Comment by Chadh13** [comment]
^ is an accidental ref. I was experiencing a similar error however it is specifically with the array_formatter, not the hash_formatter... not entirely sure how to remove the ref. Sorry!

**Comment by bceppi** [comment]
Hi! I'm having the same problem. Is there any workaround for this for an app with awesome_print installed through the Gemfile?

**Comment by araslanov-e** [comment]
+1

**Comment by LucasKuhn** [comment]
+1

**Comment by stdedos** [comment]
You are aware that commenting "+1" doesn't help, makes no difference, and it's spamming us with a useless message, right?

There is this
![image](https://user-images.githubusercontent.com/133706/92275208-61997080-eef7-11ea-95e5-97ddf833347e.png)
neat little button, which you can press to add your "participation" to the issue

**Comment by febeling** [comment]
This commit https://github.com/ruby/irb/commit/c5ea79d5cecea9cae6ad0c1f31703a98cd329431 in IRB change the signature of IRB::Irb#output_value to add one default argument. 

When overriding the method in awesome_print without this default parameter, the error is raise.

**Comment by febeling** [comment]
I just realize this issue is not about the ArgumentError that I was experiencing. The one I encountered (and fixed in the PR) is avoided by disabling awesome_print support for IRB. This is probably the one @sunsations saw too, but that seems to be a separate issue. That issue would be fixed by my fix/PR (closed now).

**Comment by febeling** [comment]
I think I'm at the bottom of this. net/http's Net::HTTPGenericRequest has an attribute with a reader [`method`](https://github.com/ruby/ruby/blob/master/lib/net/http/generic_request.rb#L55); that conflicts with Ruby's core [`Object#method(sym)` ](https://ruby-doc.org/core-2.7.2/Object.html#method-i-method).

Now awesome_print in the fallback_formatter converts objects to hashes for output. It relies on Object#method to check for that here: https://github.com/awesome-print/awesome_print/blob/awesomeprint2/lib/awesome_print/formatters/fallback_formatter.rb#L41 (for the version 2 branch, which is pre-released).

How to fix this? The real problem is the net/http class shadowing Object#method. I don't see an easy general fix. Possibly add another special formatter to awesome_print, as there are some already for other classes (24 files for various ruby core classes, I don't see any stdlib formatters for now)?
