### ISSUE TITLE
V2: uninitialized constant AwesomePrint::Formatters::SetFormatter::Set 

### ISSUE THREAD

**Issue by sshaw** [awesome-print/awesome_print#351]
2.0.0.pre2:

```
~ >ruby -rawesome_print -e'ap({:a => 1})'
/Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatters/set_formatter.rb:10:in `formattable?': uninitialized constant AwesomePrint::Formatters::SetFormatter::Set (NameError)
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatter.rb:49:in `block in format'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatter.rb:44:in `each'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatter.rb:44:in `format'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/inspector.rb:118:in `unnested'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/inspector.rb:76:in `awesome'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatters/hash_formatter.rb:96:in `pre_ruby19_syntax'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatters/hash_formatter.rb:56:in `block (2 levels) in printable_hash'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/indentator.rb:13:in `indent'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/inspector.rb:65:in `increase_indentation'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatters/base_formatter.rb:80:in `indented'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatters/hash_formatter.rb:52:in `block in printable_hash'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatters/hash_formatter.rb:51:in `map!'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatters/hash_formatter.rb:51:in `printable_hash'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatters/hash_formatter.rb:40:in `multiline_hash'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatters/hash_formatter.rb:23:in `format'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/formatter.rb:41:in `format'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/inspector.rb:118:in `unnested'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/inspector.rb:76:in `awesome'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/core_ext/kernel.rb:5:in `ai'
	from /Users/sshaw/.rvm/gems/ruby-2.3.7/gems/awesome_print-2.0.0.pre2/lib/awesome_print/core_ext/kernel.rb:15:in `ap'
	from -e:1:in `<main>'
```

**Comment by sshaw** [comment]
Looks like `set_formatter.rb` needs to `require "set"`.

**Comment by sshaw** [comment]
ruby-2.3.7. 

Nothing in stdlib (https://ruby-doc.org/stdlib-2.6/) is automatically required.
